import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { loadConfig, resolvePath } from './config';

/**
 * Generate TypeScript types from .proto files
 *
 * This uses protobufjs-cli (pbjs/pbts) to generate types and then
 * applies transforms to make them more ergonomic for protobus usage.
 */
export async function generateTypes(cwd: string = process.cwd()): Promise<void> {
    const config = loadConfig(cwd);
    const protoDir = resolvePath(config.protoDir, cwd);
    const typesOutput = resolvePath(config.typesOutput, cwd);

    // Ensure output directory exists
    const outputDir = path.dirname(typesOutput);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Scratch space for intermediate files. mkdtemp gives each run its own
    // directory: concurrent runs must not share one, and the cleanup below is
    // a recursive force delete that must never point at a predictable path.
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'protobus-'));

    const tempJsOutput = path.join(tempDir, 'proto.js');
    const tempTsOutput = path.join(tempDir, 'proto.d.ts');

    try {
        // Dynamic import of protobufjs-cli
        let pbjs: any;
        let pbts: any;

        try {
            pbjs = require('protobufjs-cli/pbjs');
            pbts = require('protobufjs-cli/pbts');
        } catch {
            // Throw, don't exit: this is a reusable function. Only the
            // command wrapper decides the process should die.
            throw new Error(
                'protobufjs-cli is required for type generation. ' +
                'Install it with: npm install --save-dev protobufjs-cli',
            );
        }

        const protoGlob = path.join(protoDir, '*.proto');

        // Check if proto directory exists
        if (!fs.existsSync(protoDir)) {
            throw new Error(
                `Proto directory not found: ${protoDir}. Create it and add your .proto files, ` +
                'or configure "protoDir" in package.json',
            );
        }

        // Check if proto files exist
        const protoFiles = fs.readdirSync(protoDir).filter(f => f.endsWith('.proto'));
        if (protoFiles.length === 0) {
            throw new Error(`No .proto files found in ${protoDir}`);
        }

        console.log(`Found ${protoFiles.length} proto file(s) in ${protoDir}`);

        // Step 1: Generate JS with pbjs
        console.log('Generating JavaScript definitions...');
        await new Promise<void>((resolve, reject) => {
            pbjs.main([
                '--target', 'static',
                '--no-convert',
                '--no-encode',
                '--no-decode',
                '--no-verify',
                '--no-delimited',
                '--no-beautify',
                '--no-create',
                '--keep-case',
                '-w', 'commonjs',
                '--es6',
                '-o', tempJsOutput,
                protoGlob,
            ], (err: Error | null) => {
                if (err) reject(err);
                else resolve();
            });
        });

        // Step 2: Generate TypeScript definitions with pbts
        console.log('Generating TypeScript definitions...');
        await new Promise<void>((resolve, reject) => {
            pbts.main([
                '-o', tempTsOutput,
                '--no-comments',
                '-m',
                tempJsOutput,
            ], (err: Error | null) => {
                if (err) reject(err);
                else resolve();
            });
        });

        // Step 3: Transform the TypeScript output
        console.log('Transforming types for protobus...');
        let tsContent = fs.readFileSync(tempTsOutput, 'utf-8');
        tsContent = transformTypes(tsContent);

        // Write final output
        fs.writeFileSync(typesOutput, tsContent);

        console.log(`Types generated successfully: ${typesOutput}`);

    } finally {
        // Cleanup temp directory
        if (fs.existsSync(tempDir)) {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    }
}

/**
 * Transform the generated TypeScript to be more ergonomic for protobus
 */
function transformTypes(content: string): string {
    let result = content;

    // Add header with lint disables, the call-option imports the rewritten
    // method signatures below refer to, and the 64-bit scalar alias.
    result = `/* eslint-disable */
/* tslint:disable */
// Auto-generated by protobus CLI - do not edit manually
import type { CallOptions, StreamOptions } from 'protobus';

/**
 * A 64-bit protobuf scalar (int64, uint64, sint64, fixed64, sfixed64).
 *
 * Encoding accepts a number or a decimal string. Decoding always yields a
 * decimal string, because the range of these types exceeds what a JavaScript
 * number represents exactly. Narrow before use:
 *
 *     const total = BigInt(response.amount);
 */
type Long = string;

${result}`;

    // Remove methods with callback param (we use promises)
    result = result.replace(/^.*\b(callback)\b.*$/gm, '');

    // Remove interface and service constructors
    result = result.replace(/^.*\b(constructor)\b.*$/gm, '');

    // Convert service classes to interfaces (stop extending $protobuf.rpc.Service),
    // keeping each service's own name. Renaming every one to `Service` made
    // two services in a package collide, and pinned `service Math` to a name
    // the bus does not use. The interface merges with the namespace of the
    // same name that holds its method types.
    result = result.replace(/class (\w+) extends \$protobuf.rpc.Service /gm, 'interface $1 ');

    // Export all interfaces
    result = result.replace(/\binterface /gm, 'export interface ');

    // Export all classes as ambient declarations
    result = result.replace(/\bclass /gm, 'export declare class ');

    // Export all namespaces
    result = result.replace(/\s\snamespace /gm, '  export namespace ');

    // Export the type aliases too. The Service interface refers to each method
    // by `<package>.<Service>.<method>`, so leaving those aliases unexported
    // made the whole file fail to compile at the first service it declared.
    // Indentation is the test for "inside a namespace": the Long alias in the
    // header is at column zero and stays module-local.
    result = result.replace(/^([ \t]+)type /gm, '$1export type ');

    // Export all enums
    result = result.replace(/\benum /gm, 'export enum ');
    result = result.replace(/\bconst enum /gm, 'export const enum ');

    // Remove public keyword (not needed in interfaces)
    result = result.replace(/\bpublic /gm, '');

    // Make service methods return interfaces (IFoo instead of Foo)
    const interfaceRegex = /Promise<[^>]*\./g;
    const positions: number[] = [];
    while (interfaceRegex.exec(result) !== null) {
        positions.push(interfaceRegex.lastIndex);
    }
    // Insert 'I' at each position (in reverse to not mess up indices)
    for (let i = positions.length - 1; i >= 0; i--) {
        const pos = positions[i];
        result = result.slice(0, pos) + 'I' + result.slice(pos);
    }

    // pbjs types every method as a unary promise taking one argument, because
    // that is the shape of protobufjs's own rpc.Service. ServiceProxy installs
    // two different shapes: a server-streaming method returns an AsyncIterable
    // and takes a stream idle timeout, a unary one returns a promise and takes
    // the rpc/timeout arguments. The emitted `responseStream` metadata says
    // which the schema declared, so the signature can follow it.
    result = result.replace(
        /(type \w+ = \{)([\s\S]*?)(\n[ \t]*\};)/g,
        (match, open: string, body: string, close: string) => {
            const call = /\n([ \t]*)\(request: ([\w.$]+)\): Promise<([\w.$]+)>;/.exec(body);
            if (!call) { return match; }
            const [line, indent, requestType, responseType] = call;
            const args = /readonly responseStream: true;/.test(body)
                ? `request: ${requestType}, actor?: string, idleTimeoutMs?: number, options?: StreamOptions`
                : `request: ${requestType}, actor?: string, rpc?: boolean, timeoutMs?: number, options?: CallOptions`;
            const returns = /readonly responseStream: true;/.test(body)
                ? `AsyncIterable<${responseType}>`
                : `Promise<${responseType}>`;
            return open + body.replace(line, `\n${indent}(${args}): ${returns};`) + close;
        },
    );

    return result + serviceNameDeclarations(result);
}

/**
 * The bus name of every service, as constants in its package's namespace.
 *
 * Each method's type carries `readonly path: "/<package>.<Service>/<method>"`,
 * which names the service exactly, dotted packages included, so nothing has to
 * re-parse the schema or guess. The declarations are appended as namespace
 * blocks of their own: TypeScript merges them with the generated ones, and a
 * dotted name merges with the nested namespaces pbts emits for it.
 *
 * Every service gets `<Service>ServiceName` (`ServiceName` for a service
 * called `Service`, as before). A package with exactly one service also gets
 * the established `ServiceName` and a `Service` alias, so code written against
 * those names keeps compiling, now with the name the bus actually uses.
 */
/** The constant holding a service's bus name: `ServiceName` for `Service`, else `<Name>ServiceName`. */
export function serviceNameConstant(service: string): string {
    return service === 'Service' ? 'ServiceName' : `${service}ServiceName`;
}

function serviceNameDeclarations(source: string): string {
    const byPackage = new Map<string, Set<string>>();
    for (const m of source.matchAll(/readonly path: "\/([\w.]+)\/\w+";/g)) {
        const full = m[1];
        const dot = full.lastIndexOf('.');
        if (dot < 0) continue;
        const pkg = full.slice(0, dot);
        (byPackage.get(pkg) || byPackage.set(pkg, new Set()).get(pkg)!).add(full.slice(dot + 1));
    }
    const blocks: string[] = [];
    for (const [pkg, services] of byPackage) {
        const lines = [...services].map(name => `    export const ${serviceNameConstant(name)} = '${pkg}.${name}' as const;`);
        if (services.size === 1) {
            const [only] = services;
            if (only !== 'Service') {
                lines.push(`    export const ServiceName = '${pkg}.${only}' as const;`);
                lines.push(`    export type Service = ${only};`);
            }
        }
        blocks.push(`export namespace ${pkg} {\n${lines.join('\n')}\n}\n`);
    }
    return blocks.length ? `\n${blocks.join('\n')}` : '';
}

// Allow running directly
if (require.main === module) {
    generateTypes().catch(err => {
        console.error('Error generating types:', err);
        process.exit(1);
    });
}
