syntax = "proto3";
package Orders;

message CreateOrderRequest {
    string user_id = 1;
    repeated string skus = 2;
}

message CreateOrderResponse {
    string order_id = 1;
}

message ShipOrderRequest {
    string order_id = 1;
    string region = 2;
    string carrier = 3;
}

message ShipOrderResponse {
    bool ok = 1;
}

message OrderCreated {
    string order_id = 1;
    string user_id = 2;
    int64  created_at = 3;
    repeated string skus = 4;
}

message OrderShipped {
    string order_id = 1;
    string carrier = 2;
    string region = 3;
}

service Service {
    rpc createOrder(Orders.CreateOrderRequest) returns(Orders.CreateOrderResponse);
    rpc shipOrder(Orders.ShipOrderRequest) returns(Orders.ShipOrderResponse);
}
